### ISSUE TITLE
Betting or career mode

### ISSUE THREAD

**Issue by lykkin** [chonny24/horse-racing#2]
i'd like a bit more interactive choices

i could see this game evolving into the perspective of a bookie, a gambler, or a jockey/manager with the social dramas that follow.

**Comment by lykkin** [comment]
plz

**Comment by jonmerrill2012** [comment]
It would be fun

**Comment by lykkin** [comment]
don't taunt me like that

**Comment by jonmerrill2012** [comment]
HORSE

**Comment by jonmerrill2012** [comment]
RACE

**Comment by jonmerrill2012** [comment]
done.
